name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=my-docker-app
        IMAGE_TAG=${{ github.run_number }}
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest .

    - name: Push Docker image
      run: |
        IMAGE_NAME=my-docker-app
        IMAGE_TAG=${{ github.run_number }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

    - name: Run container
      run: |
        IMAGE_NAME=my-docker-app
        IMAGE_TAG=${{ github.run_number }}
        docker run -d -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
